In [27]:
import numpy as np
import rotations as rots


This whole exercise is to basically prove that you can linear interpolate using DCM's.


In [28]:
def linearInterpolate (R1, R2, t):
    return (R1*(1-t) + R2 *t)

In [29]:
R1 = rots.rotationX(30.0)
R2 = rots.rotationX(130.0)

print("R1 {}".format(R1))
print("R2 {}".format(R2))


R1 [[ 1.         0.         0.       ]
 [ 0.         0.8660254  0.5      ]
 [ 0.        -0.5        0.8660254]]
R2 [[ 1.          0.          0.        ]
 [ 0.         -0.64278761  0.76604444]
 [ 0.         -0.76604444 -0.64278761]]


In [30]:
R_interp = linearInterpolate(R1, R2, 0.5)
print("R_interpolated {}".format(R_interp))

R_interpolated [[ 1.          0.          0.        ]
 [ 0.          0.1116189   0.63302222]
 [ 0.         -0.63302222  0.1116189 ]]


In [49]:
R_interp_det =  np.linalg.det(R_interp)
R_interp_eye = np.matmul(R_interp, np.transpose(R_interp))

print("R_inter_det {}\n".format(R_interp_det))
print("R_inter_eye {}\n".format(R_interp_eye))  # this should be identity if valid rotation matrix

print("eye: {}\n".format(np.identity(3)))

# This is not a valid rotation matrix
# the transpose does not equal the inverse.  
assert(R_interp_det != 1)


R_inter_det 0.4131759111665348

R_inter_eye [[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 4.13175911e-01 6.69020536e-18]
 [0.00000000e+00 6.69020536e-18 4.13175911e-01]]

eye: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



AssertionError: 

In [50]:
R_truth = rots.rotationX(80.0) # this is halfway between 30 and 130
print("truth {}".format(R_truth))

truth [[ 1.          0.          0.        ]
 [ 0.          0.17364818  0.98480775]
 [ 0.         -0.98480775  0.17364818]]
