In [9]:
import numpy as np

def rotationX(theta):
    return np.array([[1,0,0,],
                    [0,  np.cos(theta), np.sin(theta) ],
                    [0, -np.sin(theta),np.cos(theta) ]])

def rotationY(theta):
    return np.array([[np.cos(theta),0, -np.sin(theta)],
                    [0, 1, 0 ],
                    [np.sin(theta), 0, np.cos(theta) ]])

def rotationZ(theta):
    return np.array([[np.cos(theta) , np.sin(theta), 0  ],
                    [-np.sin(theta), np.cos(theta), 0  ],
                    [0, 0, 1 ]])

def radToDeg(rad):
    return rad * (180.0/np.pi)

def degToRad(deg):
    return deg * (np.pi/180.0)

def rotationEulerXYZ(phi, theta, psi):
    Rx = rotationX(phi)
    Ry = rotationY(theta)
    Rz = rotationZ(psi) 
    R = np.matmul(Rx, np.matmul(Ry, Rz))
    return R

def rotationEulerZXZ(phi, theta, psi):
    Rz2 = rotationZ(phi)
    Rx = rotationX(theta)
    Rz1 = rotationZ(psi) 
    R = np.matmul(Rz2, np.matmul(Rx, Rz1))
    return R

def eulerAngleFromRotZXZ(Rzxz):
    phi   = np.arctan2(Rzxz[0][2], Rzxz[1][2])
    theta = np.arccos(Rzxz[2][2])
    psi   = np.arctan2(Rzxz[2][0], -Rzxz[2][1])
    return (phi, theta, psi)

def eulerAngleFromRotXYZ(Rxyz):
    phi   = np.arctan2(Rxyz[1][2], Rxyz[2][2])
    theta = -np.arcsin(Rxyz[0][2])
    psi   = np.arctan2(Rxyz[0][1], Rxyz[0][0])
    return (phi, theta, psi)

def eulerAngleSequenceXYZ_to_ZXZ(phi, theta, psi):
    // todo:



phi_deg    = -30
theta_deg  = 65.0
psi_deg    = -45

print(f"Euler [{phi_deg},  {theta_deg},  {psi_deg}]")

phi    = degToRad(phi_deg)
theta  = degToRad(theta_deg)
psi    = degToRad(psi_deg)

print(f"Euler [{phi},  {theta},  {psi}]")

Rxyz = rotationEulerXYZ(phi, theta, psi)
print(f"Rxyz: {Rxyz}")

attitude = eulerAngleFromRotXYZ(Rxyz)
print(f"euler: {attitude}")
print(f"phi: {radToDeg(attitude[0])}")
print(f"theta: {radToDeg(attitude[1])}")
print(f"psi: {radToDeg(attitude[2])}")


Rzxz = rotationEulerZXZ(phi,theta, psi)
print(f"Rzxz: {Rzxz}")

attitude  = eulerAngleFromRotZXZ(Rzxz)
print(f"euler: {attitude}")
print(f"phi: {radToDeg(attitude[0])}")
print(f"theta: {radToDeg(attitude[1])}")
print(f"psi: {radToDeg(attitude[2])}")








Euler [-30,  65.0,  -45]
Euler [-0.5235987755982988,  1.1344640137963142,  -0.7853981633974483]
Rxyz: [[ 0.29883624 -0.29883624 -0.90630779]
 [ 0.29194424  0.93280063 -0.21130913]
 [ 0.9085513  -0.20144452  0.36599815]]
euler: (np.float64(-0.5235987755982988), np.float64(1.1344640137963142), np.float64(-0.7853981633974483))
phi: -29.999999999999996
theta: 65.0
psi: -45.0
Rzxz: [[ 0.46295432 -0.76179056 -0.45315389]
 [ 0.61235316 -0.09475362  0.78488557]
 [-0.64085638 -0.64085638  0.42261826]]
euler: (np.float64(-0.5235987755982988), np.float64(1.1344640137963142), np.float64(-0.7853981633974482))
phi: -29.999999999999996
theta: 65.0
psi: -44.99999999999999


In [10]:
phi_deg    = -30
theta_deg  = 65.0
psi_deg    = -45

Rxyz = rotationEulerXYZ(phi, theta, psi)
att_zxz = eulerAngleFromRotZXZ(Rxyz)
print(f"euler: {att_zxz}")
print(f"phi: {radToDeg(att_zxz[0])}")
print(f"theta: {radToDeg(att_zxz[1])}")
print(f"psi: {radToDeg(att_zxz[2])}")


euler: (np.float64(-1.7998580174521475), np.float64(1.1960911791866526), np.float64(1.3526054716345917))
phi: -103.12426812279172
theta: 68.53097648022109
psi: 77.4985848709643
