In [24]:
import numpy as np

rads = np.pi / 108.0

def rotationX(theta):
    matrix = np.array([[1,0,0],
                       [0, np.cos(theta), np.sin(theta) ],
                       [0, -np.sin(theta), np.cos(theta)]])
    return matrix


x_a = np.array([0,1,0])
print("x_a {}\n".format(x_a))  

# define two rotation matrices
R_ba = rotationX(30.0 * (np.pi / 180.0))
R_cb = rotationX(15.0 * (np.pi / 180.0))

print("R_ba {}\n".format(R_ba))
print("R_cb {}\n".format(R_cb))

# apply first rotation 
x_b = np.matmul(R_ba, x_a)
print("x_b {}\n".format(x_b))

# apply second rotation 
x_c = np.matmul(R_cb, x_b)
print("x_c {}\n".format(x_c))  # vector after two discrete rotations

# now we shortcut and build this into a single matrix
R_ca = np.matmul(R_cb, R_ba)
print("R_ca {}\n".format(R_ca))

# result is the same as x_c but only one matrix step
X_c2 = np.matmul(R_ca, x_a)
print("X_c2 {}\n".format(X_c2))

assert(X_c2.all() == x_c.all())

R_x45 = rotationX(45.0 * (np.pi / 180.0))
r_x = np.matmul(R_x45, x_a)
print("r_x45 {}\n".format(r_x))
assert(X_c2.all() == r_x.all())



x_a [0 1 0]

R_ba [[ 1.         0.         0.       ]
 [ 0.         0.8660254  0.5      ]
 [ 0.        -0.5        0.8660254]]

R_cb [[ 1.          0.          0.        ]
 [ 0.          0.96592583  0.25881905]
 [ 0.         -0.25881905  0.96592583]]

x_b [ 0.         0.8660254 -0.5      ]

x_c [ 0.          0.70710678 -0.70710678]

R_ca [[ 1.          0.          0.        ]
 [ 0.          0.70710678  0.70710678]
 [ 0.         -0.70710678  0.70710678]]

X_c2 [ 0.          0.70710678 -0.70710678]

r_x45 [ 0.          0.70710678 -0.70710678]

